include $(CONSOLE)/$(UI_DIR_NAME)/$(LVGL_DIR_NAME)/demos/lv_demos.mk
include $(CONSOLE)/$(UI_DIR_NAME)/$(LVGL_DIR_NAME)/examples/lv_examples.mk
include $(CONSOLE)/$(UI_DIR_NAME)/$(LVGL_DIR_NAME)/src/core/lv_core.mk
include $(CONSOLE)/$(UI_DIR_NAME)/$(LVGL_DIR_NAME)/src/draw/lv_draw.mk
include $(CONSOLE)/$(UI_DIR_NAME)/$(LVGL_DIR_NAME)/src/extra/lv_extra.mk
include $(CONSOLE)/$(UI_DIR_NAME)/$(LVGL_DIR_NAME)/src/font/lv_font.mk
include $(CONSOLE)/$(UI_DIR_NAME)/$(LVGL_DIR_NAME)/src/hal/lv_hal.mk
include $(CONSOLE)/$(UI_DIR_NAME)/$(LVGL_DIR_NAME)/src/misc/lv_misc.mk
include $(CONSOLE)/$(UI_DIR_NAME)/$(LVGL_DIR_NAME)/src/widgets/lv_widgets.mk
